<a href="https://colab.research.google.com/github/SanjanaCN/fmml2021/blob/main/10_Problem_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Madagascar problem

In [1]:
import numpy as np

In [2]:
A = np.array([[20, 122, 20], [35,180, 35],[50, 220, 65], [70, 300, 30]])
x = np.array([[0.05], [0.002], [0.02]])

In [ ]:
# 4x3 . 3x1 = 4x1

In [3]:
y = np.matmul(A,x) 

In [4]:
y

array([[1.644],
       [2.81 ],
       [4.24 ],
       [4.7  ]])

In [7]:
# we have to check those which are greater than 4, here we are doing a scalar subtraction
y = np.matmul(A,x) -4.0

In [6]:
y # values which are greater than zero should be considered

array([[-2.356],
       [-1.19 ],
       [ 0.24 ],
       [ 0.7  ]])

In [8]:
Z = np.hstack((A,y))

In [9]:
Z

array([[ 2.000e+01,  1.220e+02,  2.000e+01, -2.356e+00],
       [ 3.500e+01,  1.800e+02,  3.500e+01, -1.190e+00],
       [ 5.000e+01,  2.200e+02,  6.500e+01,  2.400e-01],
       [ 7.000e+01,  3.000e+02,  3.000e+01,  7.000e-01]])

In [10]:
def RankArray(A,x):
  y = np.dot(A,x) - 4.0
  L = np.hstack((A,y))
  return L

In [11]:
print (RankArray(A,x)) # here at the extreme right, the values which are greater than zero are those who should be vaccinated first

[[ 2.000e+01  1.220e+02  2.000e+01 -2.356e+00]
 [ 3.500e+01  1.800e+02  3.500e+01 -1.190e+00]
 [ 5.000e+01  2.200e+02  6.500e+01  2.400e-01]
 [ 7.000e+01  3.000e+02  3.000e+01  7.000e-01]]
